# Generated by Django 5.1.4 on 2024-12-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayyabportfolio', '0007_alter_skill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(blank=True, null=True, upload_to='skill_image/'),
        ),
    ]
