# Generated by Django 5.1.4 on 2024-12-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tayyabportfolio', '0010_remove_skill_created_at_remove_skill_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skills',
        ),
    ]
